const ADD_EMAIL = 'ADD_EMAIL';

const ADD_USERNAME = 'ADD_USERNAME';

const ADD_SCORE = 'ADD_SCORE';

const TIMEOUT_GAME = 'TIMEOUT_GAME';

const SAVE_PLAYER_TIME = 'SAVE_PLAYER_TIME';

const SAVE_PLAYER_SCORE = 'SAVE_PLAYER_SCORE';

export { ADD_USERNAME,
  ADD_EMAIL, ADD_SCORE, TIMEOUT_GAME, SAVE_PLAYER_TIME, SAVE_PLAYER_SCORE };
