const ADD_EMAIL = 'ADD_EMAIL';

const ADD_USERNAME = 'ADD_USERNAME';

const TIMEOUT_GAME = 'TIMEOUT_GAME';

const SAVE_PLAYER_TIME = 'SAVE_PLAYER_TIME';

const SAVE_PLAYER_SCORE = 'SAVE_PLAYER_SCORE';

const SAVE_PLAYER_ASSERTIONS = 'SAVE_PLAYER_ASSERTIONS';

export { ADD_USERNAME,
  ADD_EMAIL, TIMEOUT_GAME, SAVE_PLAYER_TIME, SAVE_PLAYER_SCORE, SAVE_PLAYER_ASSERTIONS };
