const ADD_EMAIL = 'ADD_EMAIL';

const ADD_USERNAME = 'ADD_USERNAME';

const ADD_SCORE = 'ADD_SCORE';

const TIMEOUT_GAME = 'TIMEOUT_GAME';

export { ADD_USERNAME, ADD_EMAIL, ADD_SCORE, TIMEOUT_GAME };
